#!/usr/bin/env python3
"""Generate AGENTS.md from CLAUDE.md for Codex compatibility.

AGENTS.md is a Codex-facing projection of CLAUDE.md. It strips:
- Sprint tracker checklists (Codex doesn't need active task state)
- Autonomous execution contracts (Codex has its own execution model)
- Claude Code-specific hook references

It keeps:
- Framework description and structure
- Quick start and core patterns
- References section

And adds:
- Generated-file header warning
- Codex Notes section with tool-specific guidance

Usage:
    python scripts/render_agents_md.py
    python scripts/render_agents_md.py --source CLAUDE.md --output AGENTS.md
    python scripts/render_agents_md.py --dry-run
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

GENERATED_HEADER = """\
<!-- GENERATED by scripts/render_agents_md.py from CLAUDE.md — do not edit directly.
     Regenerate with: make agents-md
     Last generated from: CLAUDE.md -->

"""

CODEX_NOTES = """
## Codex Notes

This framework is primarily designed for **Claude Code**. When using Codex:

- **No `.claude/hooks/`** — Claude Code hooks are not available. Use git hooks
  (`hooks/commit-msg`, `hooks/pre-commit`) for commit enforcement instead.
- **CLAUDE.md convention** — Codex reads AGENTS.md; Claude Code reads CLAUDE.md.
  Both describe the same framework; AGENTS.md omits Claude-Code-specific sections.
- **Run tests:** `make test` or `python -m pytest tests/ -q`
- **Run checks:** `make check` (ruff + pytest)
- **Commit prefix:** All commits must start with `[Plan #N]`, `[Trivial]`, or `[Unplanned]`
  — enforced by git commit-msg hook.
- **Read-gating:** Claude Code's read-gating hooks enforce reading governing docs before
  editing. In Codex, apply this discipline manually: read CLAUDE.md or the relevant
  pattern before modifying coupled files.
- **Plan workflow:** Create a plan file in `docs/plans/` before implementing. See
  `patterns/15_plan-workflow.md` for the template and status lifecycle.
"""

# Sections to exclude from the generated AGENTS.md
EXCLUDED_SECTION_PATTERNS = [
    r"^## AUTONOMOUS EXECUTION CONTRACT",
    r"^Active sprint tracker:",
    r"^Phase checklist",
    r"^\*\*Sprint complete",
    r"^Rules during continuous execution:",
]

# Headers that signal "keep everything from here to end of file"
KEEP_FROM_SECTIONS = [
    "## Previously:",
    "## Structure",
    "## Quick Start",
    "## Core Patterns",
    "## References",
    "1. **Enforced Planning**",
    "2. **Enforced Context",
    "3. **Enforced Alignment",
]


def render_agents_md(claude_md_path: Path) -> str:
    """Transform CLAUDE.md into AGENTS.md content.

    Strategy: keep the framework description sections; strip sprint state
    and Claude Code-specific execution contracts.
    """
    source = claude_md_path.read_text(encoding="utf-8")
    lines = source.split("\n")

    output_lines: list[str] = []
    skip_block = False
    blank_run = 0

    i = 0
    while i < len(lines):
        line = lines[i]

        # Check if this line starts an excluded section
        is_excluded = any(re.match(pat, line.strip()) for pat in EXCLUDED_SECTION_PATTERNS)

        if is_excluded:
            # Skip until next ## section header or end of checklist block
            skip_block = True
            i += 1
            continue

        if skip_block:
            # Stop skipping when we hit a new top-level section (##) or certain markers
            if line.startswith("## ") or line.startswith("1. **Enforced Planning"):
                skip_block = False
                # Don't skip this line — fall through to output it
            else:
                i += 1
                continue

        # Collapse 3+ consecutive blank lines into 2
        if line.strip() == "":
            blank_run += 1
            if blank_run <= 2:
                output_lines.append(line)
        else:
            blank_run = 0
            output_lines.append(line)

        i += 1

    result = GENERATED_HEADER + "\n".join(output_lines).rstrip() + "\n" + CODEX_NOTES
    return result


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate AGENTS.md from CLAUDE.md")
    parser.add_argument(
        "--source",
        type=Path,
        default=Path("CLAUDE.md"),
        help="Source CLAUDE.md path (default: CLAUDE.md in current directory)",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("AGENTS.md"),
        help="Output AGENTS.md path (default: AGENTS.md in current directory)",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print output to stdout instead of writing file",
    )
    args = parser.parse_args()

    if not args.source.exists():
        print(f"Error: source file not found: {args.source}", file=sys.stderr)
        return 1

    content = render_agents_md(args.source)

    if args.dry_run:
        print(content)
        return 0

    # Break symlink before writing so we don't clobber the source file.
    if args.output.is_symlink():
        args.output.unlink()

    args.output.write_text(content, encoding="utf-8")
    print(f"Generated {args.output} from {args.source} ({len(content)} chars)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
